# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "centos/7"
    ansible.vm.hostname = "ansible-server"
    ansible.vm.network "private_network", ip: "192.168.33.10"
    ansible.vm.provision "shell", inline: <<-SHELL
      sudo yum install git -y
      sudo yum install ansible -y
      sudo yum install epel-release -y
      sudo yum install python-pip -y
      sudo pip install --upgrade pip
      sudo pip install boto3
      sudo mkdir /workspace
      sudo chown vagrant /workspace
      sudo chgrp vagrant /workspace
    SHELL
  end

  config.vm.define "ci" do |ci|
    ci.vm.box = "centos/7"
    ci.vm.hostname = "ci-server"
    ci.vm.network "private_network", ip: "192.168.33.11"
  end

end
