# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "centos/7"
    ansible.vm.hostname = "ansible-server"
    ansible.vm.network "private_network", ip: "192.168.33.10"
    ansible.vm.provision "file", source: "~/Workspace/Mine/oh-my-devops/vagrant/keys", destination: "$HOME/.ssh"
    ansible.vm.provision "shell", inline: <<-SHELL
      sudo yum install git -y
      sudo yum install ansible -y
      sudo rm -rf /workspace
      git clone https://github.com/tanyixiu/oh-my-devops.git /workspace/oh-my-devops
      sudo chown -R vagrant:vagrant /workspace
    SHELL

  end

  config.vm.define "ci" do |ci|
    ci.vm.box = "centos/7"
    ci.vm.hostname = "ci-server"
    ci.vm.network "private_network", ip: "192.168.33.11"
    ci.vm.provision "file", source: "~/Workspace/Mine/oh-my-devops/vagrant/keys/id_rsa.pub", destination: "$HOME/.ssh/id_rsa.pub"
    ci.vm.provision "shell", inline: <<-SHELL
      cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
      echo $'\r\t' >> /home/vagrant/.ssh/authorized_keys
      rm -rf /home/vagrant/.ssh/id_rsa.pub
    SHELL
  end

end
