- name: install epel-release
  yum:
    name: epel-release
    state: latest
  become: yes

- name: install pip
  yum:
    name: python-pip
    state: latest
  become: yes

- name: install boto3
  pip:
    name: boto3
    state: latest
  become: yes

- name: create workspace directory
  file:
    path: "{{ workspace }}"
    owner: "{{ provision_user }}"
    group: "{{ provision_user }}"
    mode: 0755
    state: directory
  become: yes
