version: "3"
volumes:
  jenkins-data:
    driver: local
services:
  ci:
    image: jenkinsci/blueocean
    ports:
      - 8888:8080
    restart: always
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock