# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  config.vm.define "docker" do |docker|
    docker.vm.box = "centos/7"
    docker.vm.hostname = "docker-server"
    docker.vm.network "private_network", ip: "192.168.33.9"
    docker.vm.provision "shell", inline: <<-SHELL
      sudo yum install docker -y
      sudo yum install git -y
      sudo rm -rf /workspace
      git clone https://github.com/tanyixiu/oh-my-devops.git /workspace/oh-my-devops
      sudo chown -R vagrant:vagrant /workspace
    SHELL
  end

end