---
- name: check if java is installed
  command: "java -version"
  register: java_installed_result
  ignore_errors: true

#- include: download.yml
#  when: java_installed_result is failed
#
#- include: install.yml
#  when: java_installed_result is failed
#
#- include: config.yml
#  when: java_installed_result is failed