java_download_url: https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.tar.gz
java_archive_name: jdk-8u202-linux-x64.tar.gz
java_root_dir: /usr/share/java-1.8.0
java_jdk_dir: "{{ java_root_dir }}/jdk1.8.0_202"